INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (0, 0, '/acmpic/0', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (1, 0, '/acmpic/0', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (2, 0, '/acmpic/0', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (3, 1, '/acmpic/1', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (4, 1, '/acmpic/1', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (5, 1, '/acmpic/1', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (6, 2, '/acmpic/2', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (7, 2, '/acmpic/2', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (8, 2, '/acmpic/2', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (9, 3, '/acmpic/3', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (10, 3, '/acmpic/3', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (11, 3, '/acmpic/3', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (12, 4, '/acmpic/4', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (13, 4, '/acmpic/4', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (14, 4, '/acmpic/4', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (15, 5, '/acmpic/5', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (16, 5, '/acmpic/5', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (17, 5, '/acmpic/5', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (18, 6, '/acmpic/6', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (19, 6, '/acmpic/6', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (20, 6, '/acmpic/6', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (21, 7, '/acmpic/7', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (22, 7, '/acmpic/7', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (23, 7, '/acmpic/7', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (24, 8, '/acmpic/8', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (25, 8, '/acmpic/8', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (26, 8, '/acmpic/8', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (27, 9, '/acmpic/9', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (28, 9, '/acmpic/9', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (29, 9, '/acmpic/9', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (30, 10, '/acmpic/10', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (31, 10, '/acmpic/10', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (32, 10, '/acmpic/10', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (33, 11, '/acmpic/11', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (34, 11, '/acmpic/11', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (35, 11, '/acmpic/11', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (36, 12, '/acmpic/12', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (37, 12, '/acmpic/12', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (38, 12, '/acmpic/12', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (39, 13, '/acmpic/13', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (40, 13, '/acmpic/13', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (41, 13, '/acmpic/13', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (42, 14, '/acmpic/14', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (43, 14, '/acmpic/14', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (44, 14, '/acmpic/14', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (45, 15, '/acmpic/15', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (46, 15, '/acmpic/15', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (47, 15, '/acmpic/15', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (48, 16, '/acmpic/16', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (49, 16, '/acmpic/16', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (50, 16, '/acmpic/16', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (51, 17, '/acmpic/17', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (52, 17, '/acmpic/17', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (53, 17, '/acmpic/17', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (54, 18, '/acmpic/18', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (55, 18, '/acmpic/18', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (56, 18, '/acmpic/18', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (57, 19, '/acmpic/19', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (58, 19, '/acmpic/19', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (59, 19, '/acmpic/19', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (60, 20, '/acmpic/20', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (61, 20, '/acmpic/20', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (62, 20, '/acmpic/20', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (63, 21, '/acmpic/21', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (64, 21, '/acmpic/21', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (65, 21, '/acmpic/21', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (66, 22, '/acmpic/22', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (67, 22, '/acmpic/22', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (68, 22, '/acmpic/22', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (69, 23, '/acmpic/23', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (70, 23, '/acmpic/23', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (71, 23, '/acmpic/23', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (72, 24, '/acmpic/24', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (73, 24, '/acmpic/24', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (74, 24, '/acmpic/24', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (75, 25, '/acmpic/25', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (76, 25, '/acmpic/25', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (77, 25, '/acmpic/25', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (78, 26, '/acmpic/26', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (79, 26, '/acmpic/26', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (80, 26, '/acmpic/26', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (81, 27, '/acmpic/27', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (82, 27, '/acmpic/27', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (83, 27, '/acmpic/27', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (84, 28, '/acmpic/28', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (85, 28, '/acmpic/28', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (86, 28, '/acmpic/28', '2.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (87, 29, '/acmpic/29', '0.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (88, 29, '/acmpic/29', '1.jpg');

INSERT INTO acmpic (ACM_PICNO, ACMNO, ACM_PICURL, ACM_PICNAME) 
VALUES (89, 29, '/acmpic/29', '2.jpg');

